Add read onyl permission by codeql

diff --git a/.github/workflows/mirror.yml b/.github/workflows/mirror.yml
--- a/.github/workflows/mirror.yml
+++ b/.github/workflows/mirror.yml
@@ -6,9 +6,15 @@ on:
   delete:
   workflow_dispatch:
 
+permissions:
+  contents: read
+
 concurrency:
   group: mirrors
   cancel-in-progress: true
+
+permissions:
+  contents: read
 
 jobs:
   mirror:
@@ -34,15 +40,15 @@ jobs:
           done
 
           echo "Pushing to GitLab..."
-          git push --mirror https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/$GH_USER/$REPO.git || echo "GitLab push failed"
+          git push --mirror https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/$GH_USER/$REPO.git || echo "[warn] GitLab push failed"
 
           echo "Pushing to Codeberg..."
-          git push --mirror https://oauth2:${{ secrets.CODEBERG_TOKEN }}@codeberg.org/$LOWER_USER/$REPO.git || echo "Codeberg push failed"
+          git push --mirror https://oauth2:${{ secrets.CODEBERG_TOKEN }}@codeberg.org/$LOWER_USER/$REPO.git || echo "[warn] Codeberg push failed"
 
           echo "Pushing to Bitbucket..."
-          git push --mirror https://x-token-auth:${{ secrets.BITBUCKET_TOKEN }}@bitbucket.org/$LOWER_USER/xlade.git || echo "Bitbucket push failed"
+          git push --mirror https://x-token-auth:${{ secrets.BITBUCKET_TOKEN }}@bitbucket.org/$LOWER_USER/xlade.git || echo "[warn] Bitbucket push failed"
 
           echo "Pushing to Gitea..."
-          git push --mirror https://${{ secrets.GITEA_TOKEN }}@gitea.com/$GH_USER/$REPO.git || echo "Gitea push failed"
+          git push --mirror https://${{ secrets.GITEA_TOKEN }}@gitea.com/$GH_USER/$REPO.git || echo "[warn] Gitea push failed"
 
-          echo "All mirror attempts completed."
+          echo "[done] All mirror attempts completed."
